### ISSUE TITLE
Does it work with wireless charging?

### ISSUE THREAD

**Issue by Void48** [lich4/ChargeLimiter#14]
Thanks for the app

**Comment by lich4** [comment]
Theoretically support all kinds of charging method.
I only tested "USB Host" and PD charger

**Comment by lich4** [comment]
The charging status is maintained by 'powerd' process, powerd send status to SpringBoard then the ICON would change, and I thought It probably require a injection to powerd or SpringBoard process, which requires Jailbreak. So I didn't try to change it for complexity and feasibility.
When I am idle, I would try researching it.
