### ISSUE TITLE
CCSupport 模組

### ISSUE THREAD

**Issue by olivertzeng** [lich4/ChargeLimiter#17]
希望可以增加 CCSupport 模組以暫時停用 AlDenate。這樣是因爲有時出門前需要充滿電

**Comment by olivertzeng** [comment]
也希望 iOS 15 以上可支援插件版 AlDenate

**Comment by lich4** [comment]
> 也希望 iOS 15 以上可支援插件版 AlDenate
iOS15+可以安装TrollStore用的啊, 越狱不比安装TrollStore麻烦多了?
昨天有人问rootless版，但是能用rootless的环境一定可以用trollstore啊，反之则不行，trollstore兼容度更好我才选择这个的。

**Comment by olivertzeng** [comment]
> iOS15+可以安装TrollStore用的啊, 越狱不比安装TrollStore麻烦多了?
> 
> 昨天有人问rootless版，但是能用rootless的环境一定可以用trollstore啊，反之则不行，trollstore兼容度更好我才选择这个的。

因為 CCSupport 只支援插件
所以如果將 CCSupport 功能加入到 AlDenate 那必須使用插件版

**Comment by olivertzeng** [comment]
> > 也希望 iOS 15 以上可支援插件版 AlDenate
> 
> iOS15+可以安装TrollStore用的啊, 越狱不比安装TrollStore麻烦多了?Dopamine越狱也得先有TrollStore吧？我没搞懂iOS15+需要deb的原因是什么
> 
> 昨天有人问rootless版，但是能用rootless的环境一定可以用trollstore啊，反之则不行，trollstore兼容度更好我才选择这个的。

對了雖然 rootless 一定可以安裝 trollstore 但是有些 rootless 越獄（像是palera1n）不一定有 CoreTrust 漏洞，必須額外安裝 TrollStore 可能對某些然來說會有點麻煩
所以建議 trollstore rootless rootful 都提供

**Comment by lich4** [comment]
“因爲有時出門前需要充滿電”， 如果只是这个需求，只需要在App里停止服务即可，关闭后即可恢复充电。
目前恢复充电的途径有：
1. 卸载AlDente
2. AlDente中停止服务
3. 边缘触发模式下到达阈值下限(受阈值上限约束)
4. 插电即充模式下新插入电源(受阈值上限约束)

**Comment by lich4** [comment]
> > > 也希望 iOS 15 以上可支援插件版 AlDenate
> > 
> > 
> > iOS15+可以安装TrollStore用的啊, 越狱不比安装TrollStore麻烦多了?Dopamine越狱也得先有TrollStore吧？我没搞懂iOS15+需要deb的原因是什么
> > 昨天有人问rootless版，但是能用rootless的环境一定可以用trollstore啊，反之则不行，trollstore兼容度更好我才选择这个的。
> 
> 對了雖然 rootless 一定可以安裝 trollstore 但是有些 rootless 越獄（像是palera1n）不一定有 CoreTrust 漏洞，必須額外安裝 TrollStore 可能對某些然來說會有點麻煩 所以建議 trollstore rootless rootful 都提供

ok，这几天在休假，等我回去有测试机了再打个rootless包

**Comment by olivertzeng** [comment]
> “因爲有時出門前需要充滿電”， 如果只是这个需求，只需要在App里停止服务即可，关闭后即可恢复充电。
> 
> 目前恢复充电的途径有：
> 
> 1. 卸载AlDente
> 
> 2. AlDente中停止服务
> 
> 3. 边缘触发模式下到达阈值下限(受阈值上限约束)
> 
> 4. 插电即充模式下新插入电源(受阈值上限约束)

謝啦目前我試試看使用「停止服務」

**Comment by olivertzeng** [comment]
如果你不太清楚 CCSupport 他就是支援控制中心的模組
這樣右上角（或底下）一拉就可以暫時關閉服務了

**Comment by lich4** [comment]
> 如果你不太清楚 CCSupport 他就是支援控制中心的模組 這樣右上角（或底下）一拉就可以暫時關閉服務了

CCSupport我记得是越狱环境下的吧。如果加CCSupport不如加个TrollSpeed那种悬浮窗了，还通用。
后面有时间我再开发，假期结束了有其他项目要做

**Comment by olivertzeng** [comment]
> > 如果你不太清楚 CCSupport 他就是支援控制中心的模組 這樣右上角（或底下）一拉就可以暫時關閉服務了
> 
> 
> 
> CCSupport我记得是越狱环境下的吧。如果加CCSupport不如加个TrollSpeed那种悬浮窗了，还通用。
> 
> 后面有时间我再开发，假期结束了有其他项目要做

TrollSpeed 是用來顯示訊息的我指的CCSupport模組是能夠暫時停用服務的模組

**Comment by lich4** [comment]
> TrollSpeed 是用來顯示訊息的我指的CCSupport模組是能夠暫時停用服務的模組

TrollSpeed也可以改造成一个按钮啊，可以实现，他就是一个窗口

**Comment by olivertzeng** [comment]
> > TrollSpeed 是用來顯示訊息的我指的CCSupport模組是能夠暫時停用服務的模組
> 
> 
> 
> TrollSpeed也可以改造成一个按钮啊，可以实现，他就是一个窗口

窗口？是我們這邊（台灣）的「視窗」嗎

**Comment by lich4** [comment]
我也不太懂你们的视窗是啥意思。我们这的窗口，就是任意一个桌面上的app的一个UI控件，都属于一个窗口，App本身是最大的一个窗口

**Comment by lich4** [comment]
悬浮窗已加
