### ISSUE TITLE
Kudos on creating your iOS tool and please respond to our email request!

### ISSUE THREAD

**Issue by MatthiasKerbl** [lich4/ChargeLimiter#24]
Hi @lich4,

Kudos on creating your iOS tool. It's great to see initiatives aimed at improving battery health awareness for iPhone users.

However, there are some issues with the naming you've chosen. Consequently, we've sent you an email to your official GitHub email address (lichao.890427@163.com) last week.
Kindly review it and respond promptly.

Regards,
Matthias

**Comment by lich4** [comment]
Okey, I have just see that, I will change to a new name

**Comment by MatthiasKerbl** [comment]
Hi @lich4,

Thank you for your understanding and the prompt reply. Please also don't forget to change the name within the app, the documentation, and so on.

Best,
Matthias

**Comment by lich4** [comment]
I have change all the string to new name, you can check now. Thanks for reminding me
