### ISSUE TITLE
是不是应该增加个自定义输入限制最高电量？

### ISSUE THREAD

**Issue by jyucoeng** [lich4/ChargeLimiter#25]
是不是应该增加个自定义输入限制最高电量？ 这样才能限制 97 98 这种？如果有必要的话？

**Comment by lich4** [comment]
增量为1的意义是什么？你的需求是什么导致增量5不够？

**Comment by lich4** [comment]
有研究表明电量在20%-80%之间,温度在10°C-35°C之间,对电池寿命影响最小.因此App上下阈值默认设定为20/80.如果自行调整还是建议在20-80之间.

**Comment by lich4** [comment]
1.4.1已增加
