### ISSUE TITLE
关于温度停止充电优化

### ISSUE THREAD

**Issue by hetmly** [lich4/ChargeLimiter#27]
达到温度条件后停止充电后，能不能过一会检测温度下来了再继续充
因为在充电的过程中看剧或者玩游戏啥的，过一会直接锁屏让它接着充，回头发现一直没冲...
现在好像温度停止充电后只能重新拔插或者手动打开充电

**Comment by lich4** [comment]
充电和停充的触发条件目前就是这样的。
温度这个我得想一下怎么搞

**Comment by hetmly** [comment]
> 充电和停充的触发条件目前就是这样的。 由于温度是不可控因素，受环境影响，所以并不适合App全权接管，否则众口难调。

我的意思不是控制温度呀。
是温度达到设置的条件停止了充电，过一会温度下降了再自动冲上，这样就不用重新拔插充电线。

比如我设置的是达到40度充电，我现在刷视频的时候35度，过一会打游戏了超过40度停止了，玩了一会不玩了，手机温度下来了35度，然后能自动继续充电。

现在是只要达到一次条件停止充电，好像就只能重复插拔数据线才可能继续充电或者手动开启充电。

当然只是一个建议，只是为了这个软件能更好的方便使用，弄不了也没关系，现在的版本已经挺好的了。

祝大佬新年快乐！

**Comment by lich4** [comment]
&emsp;&emsp;我知道你的意思。如果只考虑你的需求这个肯定是很容易做的，但是有可能这种效果做出来未知会不会有其他问题，得仔细分析一下。目前是“由于电量过低所以开始充电”和“由于插入电源所以开始充电”，这两种情况来触发充电状态，但如果是“由于温度合适所以开始充电”，触发条件有点奇怪，不知道是否会带来其他问题，比如从户外到室内导致的温度变化，这是我上面说的温度是不可控因素的意思。
&emsp;&emsp;如果我什么时候想通了这一点，确定没问题，就会加这个功能。

**Comment by hetmly** [comment]
> > > 充电和停充的触发条件目前就是这样的。 由于温度是不可控因素，受环境影响，所以并不适合App全权接管，否则众口难调。
> > 
> > 
> > 我的意思不是控制温度呀。 是温度达到设置的条件停止了充电，过一会温度下降了再自动冲上，这样就不用重新拔插充电线。
> > 比如我设置的是达到40度充电，我现在刷视频的时候35度，过一会打游戏了超过40度停止了，玩了一会不玩了，手机温度下来了35度，然后能自动继续充电。
> > 现在是只要达到一次条件停止充电，好像就只能重复插拔数据线才可能继续充电或者手动开启充电。
> > 当然只是一个建议，只是为了这个软件能更好的方便使用，弄不了也没关系，现在的版本已经挺好的了。
> > 祝大佬新年快乐！
> 
> 我记得iOS16以上系统都有高温充电保护啊，如果温度过高充电会暂停并弹出通知，个人觉得不需要软件接管控制，当然如果你是低版本系统当我没说。

跟你说的这个没有关系😂

![2ECFF73A-7368-441A-B429-7C4FC011E1BE](https://github.com/lich4/ChargeLimiter/assets/50097999/61d66a1a-8a11-4e7e-a073-eab68fc760f7)

**Comment by hetmly** [comment]
> 我知道你的意思。如果只考虑你的需求这个肯定是很容易做的，但是有可能这种效果做出来未知会不会有其他问题，得仔细分析一下。目前是“由于电量过低所以开始充电”和“由于插入电源所以开始充电”，这两种情况来触发充电状态，但如果是“由于温度合适所以开始充电”，触发条件有点奇怪和混乱，不知道是否会带来其他问题，比如从户外到室内导致的温度变化，这是我上面说的温度是不可控因素的意思。
>   如果我什么时候想通了这一点，确定没问题，就会加这个功能。

好的，了解
