### ISSUE TITLE
deb 安装后，不能冲电

### ISSUE THREAD

**Issue by ljwbh** [lich4/ChargeLimiter#28]
使用1.3deb安装，使用插电即冲模式，但插上电源后，正在冲电开关始终未能打开。

**Comment by lich4** [comment]
型号和系统多少？

**Comment by ljwbh** [comment]
IOS6S.checkra1n  IOS12.1.1

发自我的iPhone

**Comment by ljwbh** [comment]
同样使用checkra1n越狱的iphone X  ios 13.3.1 上，用deb安装，一切正常

**Comment by lich4** [comment]
OK，我测下12系统，必现的bug，我又有环境，肯定可以修复

**Comment by ljwbh** [comment]
谢 谢 ，刚才我用unc0ver，好像不支持

**Comment by ljwbh** [comment]
谢谢

**Comment by lich4** [comment]
测了下iPhone6+iOS12.5.7，未重现bug

**Comment by lich4** [comment]
你肯定是设置错了。充电受上限约束的。如果电量已经到了上限，点充电也会被取消

**Comment by ljwbh** [comment]
这个当然知道受上限限制，但我选得是插电即冲模式

**Comment by lich4** [comment]
一样的，都受上限约束。
