### ISSUE TITLE
Blocks charging after 4-5% 

### ISSUE THREAD

**Issue by iCRON862** [lich4/ChargeLimiter#30]
Hello, idk what i'm doing wrong but if i want to use the app my device battery only charging 4-5% with an original power adapter from apple. I have set the charging limit to 75% but if i want to charge from 38% it don't get past 43% after a or two hours. My battery temperature level limit is set to 30 degree but my battety is at 25 degree. I use an 14 pro max with trollstore. Any help with the settings or app use? Thx

**Comment by lich4** [comment]
Did you mean device only charging 4-5% when use this app?
Will it recover to charge normally if disable service from UI?

**Comment by iCRON862** [comment]
> Did you mean device only charging 4-5% when use this app?
> Is "Charging" toggle enabled?
> Will it recover to charge normally if toggle charging button or disable service?

Hello, yes. If i use and installing the app then this issue get occured. If i uninstall then it charges normaly. The option 'start service' crashes the app if i try to reenable the switch. I have turned on/off the 'charging' switch but the same. If i reconnect my charger then the next 4-5% get charged (35 to 40 > reconnect > 41 to 46…) Did i have missed some settings or steps?

**Comment by lich4** [comment]
Looks like when you charging a little while, the temperature grow up and exceeded 30 degree, and it stop.
This app currently only stop when high temperature arrived, and will not start charging again unless the capacity drop down to low threshhold you set.

**Comment by lich4** [comment]
1.4 released
