### ISSUE TITLE
(TS) It goes past 1~6 % from the target percentage

### ISSUE THREAD

**Issue by gototheskinny** [lich4/ChargeLimiter#31]
Example:

<details>
  <summary>SS</summary>
  
 ![image](https://github.com/lich4/ChargeLimiter/assets/51786709/153bf5c2-1a03-467a-865d-3234fc05b4dd)
 
</details>

This app is super convenient and amazing. Thank you for your work!

**Comment by lich4** [comment]
Do you use version 1.3?

**Comment by gototheskinny** [comment]
> Do you use version 1.3?

Yes.
App: 1.3 Trollstore v.
Device: iPhone 12
Version: Ios 15.0 with Xina15 1.1.8 jailbreak (i know i shouldn't use this but some tweaks that I use is only works with this JB)

**Comment by lich4** [comment]
Does the Xina jailbreak make a difference? Could you check it for me? I have not tried Xina before.
Now ChargeLimiter is driven by kernel event, so there should not be difference from target threshhold, I don't know why either.

**Comment by gototheskinny** [comment]
> Does this has sth. todo with Xina jailbreak? Could you check it for me? I have not tried Xina before.
> 
> Now ChargeLimiter is driven by kernel event, so there should not be difference from target threshhold, I don't know why either.

In xina15 if you restart your phone jb becomes disabled. Would that be enough for trying it? Bc re installing is a headache.

**Comment by gototheskinny** [comment]
%75 target without xina15 enabled:

<details>
  <summary>77%</summary>
  
 ![image](https://github.com/lich4/ChargeLimiter/assets/51786709/d8ccebc1-78d3-49e0-89c0-e69066db7e57)
  
</details>

**Comment by lich4** [comment]
There is a 120 second delay when change charging status after (equal or higher than)iPhone 8, maybe it matters? Did you check the charging status changing?

**Comment by gototheskinny** [comment]
> There is a 120 second delay when change charging status after (equal or higher than)iPhone 8, maybe it matters? Did you check the charging status changing?

No unfortunately. But I'll look for it next time. 120secs is a lot tho. I'm using the 20w Genuine Apple USB C charger, in 2 mins it'll charge the phone 2~3 percent in that time frame for sure. Should I just use the %75 target? If it's not possible to change that it'll do just fine for me %-3% is not gonna ruin everything for me.

**Comment by lich4** [comment]
I will try XINA when I am idle, too busy these days

**Comment by gototheskinny** [comment]
> I will try XINA when I am idle, too busy these days

Tried 1.4 too today. 75% target 77% result.

**Comment by Dorukyum** [comment]
I can vouch for this: v1.4, target 80%, result 82%.

**Comment by lich4** [comment]
There is currently no way to reduce the difference between target and result, and the faster it charge, the more difference, for there is always a 2min delay after changing charging status after(or equal)iPhone8. This is very different from Mac version AlDente, in which the threshhold value can be send directly to kernel to stop charging, there is no identical Power Manager Interface on iOS to do so. But there is always a hacker way to do this, is to predict the charging speed and stop before threshhold arrives, while I don't like coding this way. So I have to close the issue.

**Comment by gototheskinny** [comment]
> There is currently no way to reduce the difference between target and result, and the faster it charge, the more difference, for there is always a 2min delay after changing charging status after(or equal)iPhone8. This is very different from Mac version AlDente, in which the threshhold value can be send directly to kernel to stop charging, there is no identical Power Manager Interface on iOS to do so. But there is always a hacker way to do this, is to predict the charging speed and stop before threshhold arrives, while I don't like coding this way. So I have to close the issue.

So is this issue happening only for trollstore fast charging users? Or is it a general fast charging issue?

**Comment by lich4** [comment]
You install tipa with TrollStore, so it's have nothing to do with xina

**Comment by gototheskinny** [comment]
> You install tipa with TrollStore, so it has nothing to do with xina.
> 
> Generally the difference is 0-1%, may be your charging speed is too fast

I'm using this Apple product:
[https://www.apple.com/shop/product/MHJA3AM/A/20w-usb-c-power-adapter?fnode=e39118491d80ea3a1c9b0f96e42a40f85966c2c3e031db33b8792b96d6ac76a85e82304d95ffcd2eefd49f8f972c5aa3724b546f925a8f1577f0cee36558055e075bd37fcaabe380d0b4d1c4ccc20dac098a112fdc7e33d5f17bea92a0f9bf45](https://www.apple.com/shop/product/MHJA3AM/A/20w-usb-c-power-adapter?fnode=e39118491d80ea3a1c9b0f96e42a40f85966c2c3e031db33b8792b96d6ac76a85e82304d95ffcd2eefd49f8f972c5aa3724b546f925a8f1577f0cee36558055e075bd37fcaabe380d0b4d1c4ccc20dac098a112fdc7e33d5f17bea92a0f9bf45)
I'm not doing some extravagant weird s/it. 5w wall adapters are not that common IMO. I think this issue effects a lot of users.

**Comment by lich4** [comment]
That's a pity for not able to help you. 
There is seldom complain about high difference(most of all is 0-1%). And I do not know why your difference is so high either. I only have limited number of iDevices and system verions, so it is really hard for all users to use it without any trouble.      

This project is for my own usage at first, it is free with no ads, I wrote this when I was not too busy, and I wish I could help more people. I will try my best. If it does, then enjoy, if not, then it is a pity, may be no replacement for this kind of software.     
   
At least you can control the battery far from overcharged, right? So what's the meaning for the difference? Most complains about this software is lose control of stopping charging due to unofficial battery installed, thats really a headache, I cannot help them for I do not have that kind of battery.

**Comment by gototheskinny** [comment]
> That's a pity for not able to help you. 
> 
> There is seldom complain about high difference(most is 0-1%). And I do not know why your difference is so high either. I only have limited number of iDevices and system verions, so it is really hard for all users to use it without any trouble.      
> 
> 
> 
> This project is for my own usage at first, it is free with no ads, I wrote this when I was not too busy, and I wish I could help more people. I will try my best(Recently I have some projects to do, which may take me three months. ). If it does help, then enjoy, if not, then it is a pity, may be no alternative for this kind of software.     
> 
>    
> 
> At least you can control the battery far from overcharged, right? So what's the meaning for the difference? Most complains about this software not able to stopp charging due to unofficial battery installed, thats really a headache, I cannot help them for this app not support that kind of battery indeed.     

There's no alternative to this app for ios 15.0>. I'm super grateful for your work and this app/tweak made my charging experience so much better than it was. I'm just saying that 20w chargers are super common these days, I'm not the only one but it's not for us it's your time and it's for you first.  I get it. I'm just lowering the target % to 75% and to results that I get are 76~79% (overnight ofc) so it's not over 80%! I can work with that. I hope you can fix or change the app for %100 accuracy down the line.

**Comment by lich4** [comment]
This is not a kind of bug or sth. just due to hardware limitation of battery and system kernel.

**Comment by gototheskinny** [comment]
> The 120 second delay is not a kind of bug or sth. just due to hardware limitation of battery and system kernel.
> 
> I asked some users on XINA yesterday, they all have difference of 0%. Users of TrollStore or Jailbreak, never report with high difference or sth. One of them even have a InstantAmperage over 4000mA. So I don't know why yours is so high. 
> 
> This project is open for everyone to submit code, if have experience with iOS software development.

Ok thank you for checking this and even for replying. I'll use this app for sure, super convenient for me still.
