### ISSUE TITLE
关于充电模式

### ISSUE THREAD

**Issue by LeePhe** [lich4/ChargeLimiter#32]
目前使用ipad pro 12.9 m2版的，用来播放hdr视频，电缆取电功率不够会消耗电池电量，这个是正常的，但过后并不会再次补充电池电量至目标值。这是一个特性还是一个bug，希望作者解答，目前长期插电使用，希望能针对这种使用模式推出针对性的充电策略，感谢作者的努力！

**Comment by lich4** [comment]
目前触发充电的条件：
* 电量低于设定的最小值
* 插电即充模式下在未插入电源情况下插入电源
* 插电即充模式下温度低于设定的最小值(下个版本1.4支持)

目前触发停充的条件：
* 电量高于设定的最大值
* 温度高于设定的最大值

如果要达到类似MacOS AlDente的效果，例如配置为目标值80%，差异10%，则在本软件中需要设置为最大电量80%，最小电量70%

**Comment by LeePhe** [comment]
> 目前触发充电的条件：
> 
> * 电量低于设定的最小值
> * 插电即充模式下在未插入电源情况下插入电源
> * 插电即充模式下温度低于设定的最小值(下个版本1.4支持)
> 
> 目前触发停充的条件：
> 
> * 电量高于设定的最大值
> * 温度高于设定的最大值
> 
> 如果要达到类似MacOS AlDente的效果，例如配置为目标值80%，差异10%，则在本软件中需要设置为最大电量80%，最小电量70%

我好像明白你的意思了，它不会自动补充电量至目标值，但当电量掉到低于下限时会触发充电，从而补充到上限。

**Comment by lich4** [comment]
对，因为尽量减少充电次数对电池更好，所以不会无缘无故充电
