### ISSUE TITLE
【bug】iPad横屏状态下悬浮窗口文字方向不会同步改变

### ISSUE THREAD

**Issue by InnovatorPrime** [lich4/ChargeLimiter#37]
测试设备：
iPad9.7 and iPad pro 5
iPadOS 17.0 and iPadOS16.6
TrollStore 2.0.12 
chargeLimiter v 1.4 ipa

**Comment by lich4** [comment]
下一版修复

**Comment by InnovatorPrime** [comment]
> 下一版修复

另外我发现chargeLimiter 在断开充电器的情况下会间隔提示start charging，怀疑是检测电量判断出了问题？（此时的电量低于80%，且温度在条件范围内没有波动，设备是静止锁屏状态下发生的。）
我的设置如下
模式插电即充，设置高于80%停止充电，温度高于35度停止充电，温度低于30度恢复充电。充电器未连接。

**Comment by lich4** [comment]
应该是低温恢复充电那里没判段是否连电，是个bug

**Comment by Cowboy-Shuai** [comment]
> 下一版将修复的其他问题： 1.界面文字可以被选中，影响操作 2.悬浮窗不支持iOS12 由于app大体已完成，且有项目要做，后面更新将到1个月一次

消息通知中的充电状态文字能跟随App里设置界面中设置的语言吗？设置成中文后使用中文通知


![C40D34C8194DDC7293724953A55C0717](https://github.com/lich4/ChargeLimiter/assets/19619031/5ad110a9-89c7-452c-adf0-81618ffa0ac6)

![766431B4C886C3CFA6C0650FBA1A6C75](https://github.com/lich4/ChargeLimiter/assets/19619031/23f3643d-f1d6-43fa-bd1a-82afdda5b513)

**Comment by InnovatorPrime** [comment]
> 应该是低温恢复充电那里没判段是否连电，是个bug

测试出一个疑似新的bug？
当开启快速充电，启用关闭蓝牙或其他任何一项或多项。在充电开始时可以正确的关闭上面设置快速充电。但当充电完成拔掉充电器并通过手机设置手动开启蓝牙一段时间（十几秒）蓝牙会自动关闭。我需要在chargeLimiter 里手动关闭快速充电，我不确定这是正常的吗？

**Comment by lich4** [comment]
> > 应该是低温恢复充电那里没判段是否连电，是个bug
> 
> 测试出一个疑似新的bug？ 当开启快速充电，启用关闭蓝牙或其他任何一项或多项。在充电开始时可以正确的关闭上面设置快速充电。但当充电完成拔掉充电器并通过手机设置手动开启蓝牙一段时间（十几秒）蓝牙会自动关闭。我需要在chargeLimiter 里手动关闭快速充电，我不确定这是正常的吗？

这个功能只在触发充电时生效，直到充到指定电量上限。如果中途拔电则视为用户自身行为，不还原飞行模式等状态。
你说的现象我暂时还没遇到

**Comment by lich4** [comment]
> 复现流程，在我的设备上复现率是100%； 开启快速充电，设备电量在可充电区间。插入充电器开始充电，在未完充电成时拔掉充电器，然后手动开启蓝牙。十几秒后会自动关闭蓝牙。其他设置也是同操作流程。

根据你的描述，应该还是温控那块的问题。因为低温恢复充电未判断是否连电源，所以继续充电，加上开启快速充电模式，导致上述现象，你验证一下

**Comment by InnovatorPrime** [comment]
> > 复现流程，在我的设备上复现率是100%； 开启快速充电，设备电量在可充电区间。插入充电器开始充电，在未完充电成时拔掉充电器，然后手动开启蓝牙。十几秒后会自动关闭蓝牙。其他设置也是同操作流程。
> 
> 根据你的描述，应该还是温控那块的问题。因为低温恢复充电未判断是否连电源，所以继续充电，加上开启快速充电模式，导致上述现象，你验证一下

你的判断是正确的，我关闭了温度停止/开启充电，现象消失了。

**Comment by djgao234** [comment]
不是，我想问一下，我是 iPhone14 iOS16.6，开了悬浮窗功能，但是找不到悬浮窗的位置，谁能给我指一下鸭![image](https://github.com/lich4/ChargeLimiter/assets/148452992/91178a76-5d6a-453f-aa03-583522e5ecc4)

**Comment by lich4** [comment]
卸载干净再重装。readme里写了的

**Comment by djgao234** [comment]
> 卸载干净再重装。readme里写了的

好的👌，谢谢🙏

**Comment by lich4** [comment]
1.4.1已修复
