### ISSUE TITLE
[Bug] Charging notifications while not charging

### ISSUE THREAD

**Issue by iCRON862** [lich4/ChargeLimiter#38]
Hello, v1.4 works fine for now but i get notifications like 'start charging' if i'm not charging my device or if i simple running the app (not charging). Running 14 Pro max with trollstore. Thanks for future fixing.

**Comment by InnovatorPrime** [comment]
https://github.com/lich4/ChargeLimiter/issues/37#issuecomment-1952478387

**Comment by iCRON862** [comment]
> #37 (comment)

Ok, sorry i only speak english and german. Thx

**Comment by lich4** [comment]
Yes, It's a bug, you can turn notification off in system settings app temporarily if bother. It will be fixup in next version.

**Comment by lich4** [comment]
Fixed in v1.4.1
