### ISSUE TITLE
请教一下快速充电模式效益问题？

### ISSUE THREAD

**Issue by BugGust** [lich4/ChargeLimiter#40]
我注意到1.4版本新增了个“增加快速充电模式(飞行模式+降低屏幕亮度+低电量模式)”
看上去只是减少了设备外围和系统刷新的功耗，但这部分功耗占比本来就不大吧，实际收益大约是多少呢？

**Comment by lich4** [comment]
实际影响还是巨大的，尤其对于低型号，这个快速充电功能其实是为了我的一个换过电池的iPhone11开发的。
这手机在电量0-20%之间的时候充电巨慢，但是加了快速充电功能，几分钟就干到40%了。
