### ISSUE TITLE
iOS/ iPadOS 14.x trollstore works too, without jailbreak

### ISSUE THREAD

**Issue by iCRON862** [lich4/ChargeLimiter#41]
Hello, i have used the time to try it out on my non jailbreak ipad on version 14.x and see here. It works fine. Only for your desc that say 14.x requires an jailbreak to work.
![809DB5BF-EFAD-4CDB-9FB9-60D27C8F5F4F](https://github.com/lich4/ChargeLimiter/assets/39169140/1f0b8f03-0d52-4f46-90e1-dfc4395095d1)
![A8BF00D7-6C93-45BC-8945-FE87048F29DF](https://github.com/lich4/ChargeLimiter/assets/39169140/efdb79ba-76a0-45a8-9c46-a876214ac5be)
![13921C6E-710B-4FFB-B97D-CB677595D164](https://github.com/lich4/ChargeLimiter/assets/39169140/f128e74d-92fe-446e-bd76-c5db91670a88)
![AC0792AB-2656-48C8-BA95-D4C46AE807CD](https://github.com/lich4/ChargeLimiter/assets/39169140/b2260f4b-7ba0-4042-a5ec-bc3456bb3269)

**Comment by lich4** [comment]
Yes, I describe that way just for convenience. I thought tipa may work on iOS14 but not have time to test it.
