### ISSUE TITLE
UI improvements request:

### ISSUE THREAD

**Issue by Void48** [lich4/ChargeLimiter#44]
Swiping up and down is limited to 60 Hz.
No dark mode theme.
Tapping on things or changing options is laggy.

(What programming language is ChargeLimiter written in?, there’s definitely many possible improvements that can be done to make the UX better.) 🫡

**Comment by lich4** [comment]
> It’s not a problem! I still appreciate the work that’s been done to this project, and sadly I wouldn’t be able to contribute in a meaningful way since I’m only just beginning to learn programming. 🫡
Haha, that's ok, you can recommend it to your friends if useful. We can make it better together.

**Comment by lich4** [comment]
UI can now be opened in safari in v1.4.1, so this issue is done for now.
