### ISSUE TITLE
[Feture Request] Max charge speed

### ISSUE THREAD

**Issue by pazza2234** [lich4/ChargeLimiter#45]
Hello, I really like this project. But I would like to ask for a feture. I Apologize if this feels like begging and I understand if it is not possible but a mac voltage would be nice to prevent the phone from charging to fast. Please and thank you. Have a good day!

**Comment by lich4** [comment]
There is currently no way to do so. If I find it possible in the future, it will be added instantly

**Comment by pazza2234** [comment]
You where right I miss spelled feature I apologize (Evan as a American and the only language I know is English, English is stupid) anyways thanks for letting me know, and I understand that iOS can be a shitshow and some stuff you just can’t do. I hope you have a good day!

**Comment by lich4** [comment]
I recently find similar tweak as you required, powercuff. But I am too busy to upgrade and test it with TrollStore. May be one month later I will try it to see if availble with trollstore

**Comment by lich4** [comment]
It had been tested successfully with TrollStore and will be done in CL v1.6.

**Comment by mailinglists35** [comment]
@lich4 when you said "tweak", were you referring to rpetrich's powercuff tweak[1], or was it a coincidence?

if it was a coincidence, do you think you could figure out what exactly was technically the tweak doing? as the effect was that when iOS battery is at one percent, some deep low power states are triggered, if I understand correctly from rpetrich's tweak. 

It would be awesome if you could integrate that same functionality in CL. which by the way, is a brilliant piece of hard work what you've done there! 

Thank you!

[1] https://www.ios-repo-updates.com/repository/rpetrich-repo/package/com.rpetrich.powercuff/

**Comment by lich4** [comment]
Yes, you are right, the "tweak" refers to rpetrich's powercuff. 
I had deeply dig both the "thermalmonitord" process, which control thermal state foundamentally, and the powercuff tweak.
Powercuff injected into this process and can control thermal state completely on Jailbreak device, while CL use some tricks to achieve the similar effect for TrollStore, more harder. CL try it best to do so, and works well to simulate high temperature when the actual temperature is relatively low. When the actual temperature is high enough, CL can still works in some extent, In this case, CL need to compete with iOS system for controlling the thermal state by controlling "thermalmonitord" process. As for 1% you mentioned, I think it is the same.
For Jailbreak environment, a tweak can do more things like this as follows. But I think it is irrelevant to a battery management tool, so there maybe no future update for this kind of functionality.
- Specify one or more hardwares to  control in Charger/CPU/GPU//Backlight/WiFi/Radio/Speaker/Arc/...
- Specify more detailed control other than off/nominal/light/moderate/heavy, with a percentage for each hardware
- Even for TrollStore, there is still "kfd" to achieve this, in some extent, but there will be always competition with iOS system on TrollStore environment.
