### ISSUE TITLE
电流负数

### ISSUE THREAD

**Issue by chinafuckingNo1** [lich4/ChargeLimiter#46]
不在充电的时候  电流怎么会是负数的

**Comment by chinafuckingNo1** [comment]
ipad pro2021  ios15.3

**Comment by lich4** [comment]
正常的，不连电源负电流表示电池流出电(给手机供电)。连电源正电流表示电池正在进电(充电)。
如果连电源还是负的说明没在充电。
如果用本软件限制充电还有微弱电流说明你的电池已经损耗了无法完全控电
如果用本软件限制充电却限制不住电流说明你的电池硬件有问题，不支持本软件
