### ISSUE TITLE
软件是如何检测设备充电状态的？

### ISSUE THREAD

**Issue by shuke12306** [lich4/ChargeLimiter#48]
目前经常会误触发，即使没有接入充电器，也会弹出通知。在这种情况下如果开了快速充电模式，就会动不动开启飞行模式，很难受，希望能有解决方案。

**Comment by lich4** [comment]
是使用了1.4.1正式版存在的问题吗。
请描述app版本，系统，型号等基本信息

**Comment by shuke12306** [comment]
是的，iOS版本16.6.1 型号14Pro 
app版本1.4和1.4.1都出现过这个问题 

我还有一台iOS版本16.6 型号12 Pro 没出现过这个问题。会不会是手机本身有故障呢？

**Comment by lich4** [comment]
1.4.1不应该，你肯定是1.4没卸干净。1.4.1压根不会在开始充电时发通知

**Comment by shuke12306** [comment]
那应该就是了，我直接覆盖安装的
