### ISSUE TITLE
App页面上下滑动时不太流畅

### ISSUE THREAD

**Issue by reidmex** [lich4/ChargeLimiter#49]
其它App滑动丝滑顺畅，且有滑动的惯性。但Limiter上下滑动感觉很费劲，比较卡顿。
希望新版本优化一下。

**Comment by lich4** [comment]
这个是UIWebView造成的，1.4.1中增加按钮可以在safari打开，所以不再对UIWebView做优化了。

**Comment by lich4** [comment]
1.4.1已修复
