### ISSUE TITLE
刷新频率是否可以自定义？

### ISSUE THREAD

**Issue by reidmex** [lich4/ChargeLimiter#50]
目前是1秒，20秒，1分钟，10分钟。1分钟太短，10分钟又太长。
能否可以将刷新时间改成自定义，范围1-600，单位为秒，用户自己填刷新值。

**Comment by lich4** [comment]
加这个功能是因为个别人觉得app会费电(可能是心理作用)，但大多数手机上感知并不明显，1.4版中这个值其实就是1秒。这个功能可以设置前台app和悬浮窗请求频率，如果用默认1秒的刷新率不耗电的话最好开1秒的，实时刷新肯定是最好的嘛。如果刷新率设置太长了，前台app和悬浮窗反应会迟缓(但后台是实时的不用担心)，如果有强迫症可能就无法接受。
可以自行测试，如果1秒的确实费电，尝试用1分钟的。如果你确实发现1分钟的还是费电而10分钟的就是不费电，可以重启这个issue
