### ISSUE TITLE
Jailbreak Version Not Working

### ISSUE THREAD

**Issue by dreampi** [lich4/ChargeLimiter#51]
I’ve switched from the Trollstore version over to the jailbroken version. But the jailbroken version still allows the iPhone to charge pass 80%?

**Comment by lich4** [comment]
Is there only one ChargeLimiter installed on that iDevice? or install tipa and deb both?
What is your system version, and device model, and Jailbreak tool you use?
Will this happen if only install the deb version?

**Comment by Mattiasselander** [comment]
iPhone 11 PRO, Dopamine. Only the jailbreak version from Sileo. Tweak does not even load. Just shows the logo

**Comment by lich4** [comment]
Which version did you use?

**Comment by Mattiasselander** [comment]
1.4.1

**Comment by lich4** [comment]
There is no tweak in deb version. If the daemon couldn't start for any reason, app will stuck at splash screen then. Make sure uninstall old one before installing. It has been tested on Dopamine2 . If you still can't get it start, you can try:
1. remove some other tweak may crash the daemon.
2. restart system, rejailbreak.
3. switch to ealier version to see if it works

**Comment by Mattiasselander** [comment]
Turned off all other tweak with iCleaner and the tweak jumped into action. Started all the tweaks again and the tweak still works. It only wanted to start once by itself. 👍
