### ISSUE TITLE
Charging limit ignored if using temperature option

### ISSUE THREAD

**Issue by derduesentrieb** [lich4/ChargeLimiter#52]
After some testing I can confirm that the „stop charging“ threshold doesn’t work if you simultaneously use the „stop charging if temperature is above XX“ option. It only accounts for temperature then and ignores the selected charging threshold charging last the specified value.

Is this intended behavior? I‘d like to use both features at the same time. Making it charge only to 80% while also keeping temperatures low.

I’m using the .deb version on Dopamine 16.5

**Comment by lich4** [comment]
fixed in v1.4.1
