### ISSUE TITLE
Trollstore version not working

### ISSUE THREAD

**Issue by Hetyey** [lich4/ChargeLimiter#53]
Dear Lich4,

Firstly, I wanted to thank you for this fantastic tweak you developed.

However, I am unsure whether my device is unsupported or if there’s another underlying issue here. I’m currently using TrollStore, iOS 17, on an iPhone 13. I’ve testesd the application through trying to disable charging while my phone was plugged in. (I don’t know if it matters, but I even toggled on and off the optimised battery charging). If my device is unsupported, is it possible in the future to get the supportation?

Thanks in advance,
Csanád

EDIT: I somehow managed to turn off charging in the app (I reinstalled it). so now in the app and on the "floating window" it says its not charging. (but its normal that my phone thinks it’s charging right?)

**Comment by lich4** [comment]
It has been described in Readme about the "Charging" toggle(English version). 
If charging status couldn't be changed even by manually toggling the button, then the iDevice will never be supported, and seems no way to do so. It has sth. to do with the battery hardware
