### ISSUE TITLE
Instant amperage(mA)

### ISSUE THREAD

**Issue by Hetyey** [lich4/ChargeLimiter#54]
Dear creator,

First of all, I’ve just found your project recently, and I want to thank you for your tweak, it is awesome!

However, I noticed that the Insant Amperage is at between 1-2 mA, when I turn the charger off.

I’m using iPhone 13, iOS 17, TrollStore.

My question is that does this mean actual charging? because I want to leave my phone on the charger over night. If so, is it fixable? or will it automatically compensate?
![IMG_7183](https://github.com/lich4/ChargeLimiter/assets/115489259/0c287c88-3412-463e-bd81-71fb7fd274f6)

EDIT: One more thing, this might be a stupid question, but could you explain how the trigger works? because if the phone’s Instant Amperage is kept at 0 mA, how could the phone reach the lower trigger? or is it able to let the phone discharge until it reaches that level?

**Comment by lich4** [comment]
1. (There is more detail in Readme you need read first)The weak Amperage means your battery is losing control of current, normally it should be zero. For 1-2mA is too small to get fully charged, so it does not matter. It has some thing to do with your battery hardware, so software cannot fix it at all, and donot worry about that.
2. "if the phone’s Instant Amperage is kept at 0 mA, how could the phone reach the lower trigger", If iDevice need more power than adaptor can supply, then the capacity will drop, it commonly happend when use with iPad(Of course with charging status set to disable). For iPhone, the more higher model, the more current it needs, so in this case if use a 5w adaptor, it may happen too.

**Comment by Hetyey** [comment]
I see. Thank you for your help!
