### ISSUE TITLE
Is it possible to release `makefile` ?

### ISSUE THREAD

**Issue by NguyenASang** [lich4/ChargeLimiter#56]
Hello, first of all, thank you for creating this powerful and useful tweak, I really like it.

So far, your tweak works well on my iPhone 6 (iOS 12.5.7), but there are still some bugs. I wanted to fix it, but soon after, I realized that there was no `makefile` (or am I just stupid and there is another way to compile ?).

Can you release it to public ? Therefore, everyone can compile and contribute to this repository, thanks for reading.

**Comment by lich4** [comment]
If you are good at makefile, you can build one yourself, main.mm/utils.mm is enough to compile the main executable of app.
This project requires serveral tools in developing, debugging, including xcode, monkeydev, theos
To debug App with XCode, see https://github.com/lich4/debugserver_azj
To debug WebUI, see https://github.com/lich4/inspectorplus

**Comment by NguyenASang** [comment]
Thanks for the information, I will try to build it myself.

**Comment by lich4** [comment]
Makefile added! Use theos to build.

**Comment by Rombond** [comment]
> Thanks for the information, I will try to build it myself.

Did you succeed ?
I'm stuck with this error `'posix_spawn_file_actions_addchdir_np' is unavailable: not available on iOS` on line 120 of utils.mm
