### ISSUE TITLE
Unable to compile it

### ISSUE THREAD

**Issue by Rombond** [lich4/ChargeLimiter#58]
Hi guys,

I'm trying to compile it to an iPhone 15 Pro on iOS 17 using XCode.
I'm having this issues during the compilation:
`'posix_spawn_file_actions_addchdir_np' is unavailable: not available on iOS` on line 120 of utils.mm

<img width="1624" alt="Capture d’écran 2024-03-14 à 19 44 48" src="https://github.com/lich4/ChargeLimiter/assets/13875526/85552dc1-6820-4275-90d6-22c17e1c65a3">

Did i miss something ?

**Comment by lich4** [comment]
1. The __API_AVAILABLE macro is useless for Jailbreak development, you can simply remove it from header file if you don't mind.
2. Copy a header file without the macro
3. Call dlsym to get the function pointer and call it
4. ..... there are many ways to do it
