### ISSUE TITLE
電池%不顯示

### ISSUE THREAD

**Issue by CySxL** [lich4/ChargeLimiter#59]
當充電超過插電即充模式下所設定的%數後，系統原生電池%數無法在越獄狀態無法再顯示。

![image](https://github.com/lich4/ChargeLimiter/assets/15531137/9e60ae19-e7de-4a2f-b0aa-3a1ae5929585)

Tested on:
iOS 16.3
iPhone 14 Pro Max
ChargeLimiter.deb 1.4.1
Dopamine 2.0.11 W哥

**Comment by CySxL** [comment]
![image](https://github.com/lich4/ChargeLimiter/assets/15531137/48e77a45-2680-41aa-bf4e-28cfefe2ba62)


我設定chargemiliter最大值為95%
當前系統電量為98%

**Comment by CySxL** [comment]
可能為錯誤回報 持續觀察如何reproduce

**Comment by lich4** [comment]
1. 设定值和实际停止值可能会不太一样，文档中有说明
2. 系统设置里电池显示有问题不一定与CL有关，目前还没有反馈因为用CL导致原生显示问题的，deb版的CL没有注入任何系统进程里

**Comment by CySxL** [comment]
好的 謝謝您
因為我發現移除了chargLimiter之後也是相同問題
還在排錯中

**Comment by CySxL** [comment]
確定了是誤報

主因是CCPowermenu cc toggle.
