### ISSUE TITLE
Could you remove the 'cl' URL scheme you've recently added?

### ISSUE THREAD

**Issue by colorlit** [lich4/ChargeLimiter#60]
As the jailbreak detection logic is being distributed in a form of collab github repository, if any mainternancers find yours and register the URL scheme to it, it will trigger the jailbreak detection with very small gain from the scheme.

i.e. https://github.com/securing/IOSSecuritySuite/blob/master/IOSSecuritySuite/JailbreakChecker.swift

**Comment by lich4** [comment]
There are many ways to detect jailbreak. Even if without scheme, there is still http local port binded, and absolute path to be detected. If you do mind that, please roll back to version 1.4
