### ISSUE TITLE
iPhone X充电故障

### ISSUE THREAD

**Issue by tony-wang1992** [lich4/ChargeLimiter#61]
机型：iPhone X
iOS系统：16.7.6 (20H320)
越狱环境：palera1n
包管理器：sileo
ChargeLimiter版本：1.4.1

异常描述：
sileo内下载安装后，无法充电，状态栏显示电量33%，绿色充电状态标识，但无法冲入电量，拔出充电线后插入，显示充电状态，电量随时间下掉。注销后打开ChargeLimiter，充电正常，次日第二次充电至97%无法充电至100%，软件内设置了上限为100%，卸载无用。
sileo内卸载后，重启取消越狱状态，充电至98%，重新越狱，充电状态暂停至98%。
需求：如何彻底卸载ChargeLimiter

**Comment by lich4** [comment]
ChargeLimiter卸载了会自动恢复充电状态，就不存在残留。
卸载后手动重新开启自带优化充电即可
