### ISSUE TITLE
Missing features after update

### ISSUE THREAD

**Issue by cewong2** [lich4/ChargeLimiter#62]
There used to be a do not charge unless below % on 1.4 and on 1.4.1 that is no longer there. 

Also for some reason the app page doesn't let me scroll so I can only see info up to design capacity, and not the rest of the battery info or the adapter info. I've tried restarting the app and phone and it still persists.

**Comment by lich4** [comment]
"charge unless below %", this feature is for edge trigger mode, will be re-added in plug and charge mode in v1.5. 
"the app page doesn't let me scroll ", iOS17 is not compatible with WebUI in v1.4.1. so you can click the safari button on the page header left part, and view in safari

**Comment by cewong2** [comment]
Thanks for the reply. Look forward to 1.5. Hopefully you'll be able to revert the scrolling for iOS 17 without having to go through Safari as well.

**Comment by lich4** [comment]
I don't have any iDevices with iOS>=17, so I can do nothing for iOS17.
This is an opensource repository, so I wish someone would join this project.
