### ISSUE TITLE
大神我按照您的配置postinst跟prerm做一个demo一直提示路径不对

### ISSUE THREAD

**Issue by LiuSky** [lich4/ChargeLimiter#63]
![IMG_0003](https://github.com/lich4/ChargeLimiter/assets/3087745/e0ffc7c3-73c1-4730-8f6d-062b760850fe)

**Comment by LiuSky** [comment]
# preinst 在软件包被安装之前执行。用于在安装软件包之前执行一些准备工作。例如，创建所需的目录结构，检查系统依赖项，设置权限等
echo "create files: preinst"
echo "#!/bin/bash
echo 'preinst'
echo 'Clean old files...'
rm -rf /var/jb/Applications/MKDeb.app
rm -rf /var/jb/Library/LaunchDaemons/com.mike.app.mklaunchd.plist
exit 0" > Layout/DEBIAN/preinst


# prerm 在软件包被移除之前执行。通常用于在卸载软件包之前执行一些清理操作或准备工作。例如，停止相关的服务或进程，备份或清理配置文件等
echo "create files: prerm"
echo "#!/bin/bash
echo 'prerm'
echo 'Clean old files...'
launchctl unload /var/jb/Library/LaunchDaemons/com.mike.app.mklaunchd.plist
killall -9 MKDeb
killall -9 MKLaunchd
rm -rf /var/jb/Library/MKDeb
exit 0" > Layout/DEBIAN/prerm


# postrm 在软件包被移除之后执行。用于在卸载软件包之后执行一些清理操作或收尾工作。例如，删除残留文件，停止相关的服务或进程，更新系统配置等
echo "create files: postrm"
echo "#!/bin/bash

echo 'postrm'

killall -9 MKLaunchd
killall -9 MKDeb

echo \$1
if [[ \$1 == remove ]]; then
    su -c /usr/bin/uicache mobile

    declare -a cydia
    cydia=(\$CYDIA)
    if [[ \${CYDIA+@} ]]; then
        eval "\""echo 'finish:reload' >&\${cydia[0]}"\""
    else
        killall -9 SpringBoard
        echo "\""remove finish! reload SpringBoard..."\""
    fi
fi

exit 0" > Layout/DEBIAN/postrm


# postinst
echo "create files: postinst"
echo "#!/bin/bash

echo 'postinst'


chown -R root:wheel             /var/jb/Applications/MKDeb.app
chmod 777                       /var/jb/Applications/MKDeb.app/bin
chmod u+s                       /var/jb/Applications/MKDeb.app/bin/MKLaunchd
chmod 644                       /var/jb/Library/LaunchDaemons/com.mike.app.mklaunchd.plist
chown root:wheel                /var/jb/Library/LaunchDaemons/com.mike.app.mklaunchd.plist

killall -9 MKLaunchd
killall -9 MKDeb

su -c /usr/bin/uicache mobile

declare -a cydia
cydia=(\$CYDIA)
if [[ \${CYDIA+@} ]]; then
    eval "\""echo 'finish:reload' >&\${cydia[0]}"\""
else
    killall -9 SpringBoard
    echo "\""install finish! reload SpringBoard..."\""
fi
launchctl load /var/jb/Library/LaunchDaemons/com.mike.app.mklaunchd.plist
exit 0" > Layout/DEBIAN/postinst


chmod 755 Layout/DEBIAN/preinst
chmod 755 Layout/DEBIAN/postinst
chmod 755 Layout/DEBIAN/prerm
chmod 755 Layout/DEBIAN/postrm


这是我写的制作的preinst postinst  prerm postrm

**Comment by lich4** [comment]
你的无根包内部路径不对
无根越狱用monkeydev打包是改了monkeydev的，这部分不公开。
可以自己用theos打无根包

**Comment by LiuSky** [comment]
啥意思？我上面这样子配置还不行？还要去单独配置？

> 你的无根包内部路径不对 无根越狱用monkeydev打包是改了monkeydev的，这部分不公开。 可以自己用theos打无根包

**Comment by lich4** [comment]
如果用xcode+monkeydev编译，monkeydev本身不支持无根，需要自行修改兼容
用theos编译的话，需要参照ChargeLimiter_rootless改一些文件，然后用MakefileRootless编译

**Comment by LiuSky** [comment]
> 如果用xcode+monkeydev编译，monkeydev本身不支持无根，需要自行修改兼容 用theos编译的话，需要参照ChargeLimiter_rootless改一些文件，然后用MakefileRootless编译 如果不会玩无根编译，可以用有根环境测

好的。谢谢。有根我是可以没问题了。现在就是想弄个无根的deb 包安装进去。我用的是脚本。没有用xcode+monkeydev。我用的是xcode+脚本build_rootless.sh 自己写的脚本，去模拟构建Packages。有根时ok了。但是一直尝试无根怎么改都不行。不知道那个环节出了问题。😄

**Comment by LiuSky** [comment]
已解决。
