### ISSUE TITLE
Scrolling in the app itself

### ISSUE THREAD

**Issue by Hetyey** [lich4/ChargeLimiter#64]
[iOS 17.0 iPhone 13]

I don't know if its only an issue for me, but for some reason in the app I can not scroll down since the 1.4.1 update. On the webpage everything works tho. I had two versions downloaded of 1.4.1 and for the latest it doesn't work already. 
Help would be appreciated!
When I try to scroll, this happens: 
![IMG_7530](https://github.com/lich4/ChargeLimiter/assets/115489259/7ac36ffe-f0d6-47d0-9375-4fd9aa15866a)

one more thing, after the 1.5 update, I can’t seem to set the plug an charge (If I want to keep the battery at 75% I can’t, I only can charge it up to 75 and wait til it reaches 70 and then it starts charging)

**Comment by Hetyey** [comment]
I don’t know what is needed for testing but if there’s something I can help with in terms of testing, I would love to.

**Comment by lich4** [comment]
"After the 1.5 update, I can’t seem to set the plug an charge (If I want to keep the battery at 75% I can’t, I only can charge it up to 75 and wait til it reaches 70 and then it starts charging)"    Did you enable 'Control inflow'? If DisableInflow is enabled, then capacity will drop.

**Comment by Hetyey** [comment]
I understand that, but I still have to set the start and stop charging, so lets say If I set start if capacity below at 70% I can only set the stop charging to 75% at best, so if I put my phone to charge at 71% it will just keep the 71% but won’t charge it to 75% If I’m not mistaken. is there a workaround for that?

**Comment by lich4** [comment]
Did your battery not support ChargeInhibit? If ChargeInhibit is supported, it is recommend to use ChargeInhibit only, and in this way you can keep your capacity stay in 75%.
If ChargeInhibit is unsupported and DisableInflow is supported, then you need to set a max and a min threshhold.
CL is designed to reduce the charging count, so the larger the diff(max-min), the better

**Comment by lich4** [comment]
> I understand that, but I still have to set the start and stop charging, so lets say If I set start if capacity below at 70% I can only set the stop charging to 75% at best, so if I put my phone to charge at 71% it will just keep the 71% but won’t charge it to 75% If I’m not mistaken. is there a workaround for that? (sorry for a lot of questions)

If you set max=75% and min=70%, if current is 71%, cl will start charging when it drop down to 70%, and charge to 75% finally. and if current is 75%, then it will stop charging until drop down to 70%

**Comment by Hetyey** [comment]
Ah, I thought that feature was in the way I deacribed, but now I fully understand. Thanks for the rapid responses and help!
