### ISSUE TITLE
有计划支持IOS17吗

### ISSUE THREAD

**Issue by azhongzl** [lich4/ChargeLimiter#65]
有计划支持IOS17吗？手机都升级了IOS17

**Comment by lich4** [comment]
iOS17越狱，越狱工具预计在2025-2026年出现，到时我手里有系统就能支持
iOS17巨魔，我认为出现的可能性极低，如果真出了，越狱不久也能出。
非巨魔非越狱是永远不会支持的。
目前17.0巨魔是可用的，只是显示有问题。

**Comment by liulock** [comment]
本来就支持17啊，用的好好的
