### ISSUE TITLE
冬天和夏天温度差异很大，能否支持两套设置？

### ISSUE THREAD

**Issue by reidmex** [lich4/ChargeLimiter#66]
否则停止充电和开始充电的温度，得来回调来调去

**Comment by lich4** [comment]
不同地区肯定有区别，不同充电器肯定也不同(电流越大温度越高)。
真正去做考虑的很多，比如去获取地区温度这些。
不过对于一个定位为“简单App”的CL来说，目前不考虑开发智能化的工具
