### ISSUE TITLE
温度控制不起作用

### ISSUE THREAD

**Issue by wast0n** [lich4/ChargeLimiter#68]
![Uploading EAADDA6F-03D1-464C-BDEB-3276967BB9AC.png…]()
你好，设定39不充电，但是都42度了，cl还是显示正在充电。而且刷新也不及时，设定1hz，还是要等很久。

**Comment by lich4** [comment]
有的电池充电时温度跳变较快，温度是不可能绝对准确控制的.究竟什么原因导致42度还在充电，请参考5分钟图及日志/var/root/aldente.log自行判断。
关于刷新不及时，CL确实不会实时刷新，因为本身是基于电池事件的，如果更新周期设置为1秒，则最多20秒就会更新一次。如果强制实现“实时更新”，可能会出现耗电问题，弊大于利。

**Comment by wast0n** [comment]
你好 谢谢 我大概知道原理了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lich0 ***@***.***&gt;
发送时间: 2024年5月19日 20:15
收件人: lich4/ChargeLimiter ***@***.***&gt;
抄送: wast0n ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [lich4/ChargeLimiter] 温度控制不起作用 (Issue #68)





 
有的电池充电时温度跳变较快，温度是不可能绝对准确控制的.究竟什么原因导致42度还在充电，请参考5分钟图及日志/var/root/aldente.log自行判断。
 关于刷新不及时，CL确实不会实时刷新，因为本身是基于电池事件的，如果更新周期设置为1秒，则最多20秒就会更新一次。如果强制实现“实时更新”，可能会出现耗电问题，弊大于利。
