### ISSUE TITLE
Question/Request: Ability to start daemon via Shortcuts for TrollStore users

### ISSUE THREAD

**Issue by pha1n0q** [lich4/ChargeLimiter#70]
As written in the README, the daemon will be unable to automatically restart after it is closed. I had an idea where an action could be added to Shortcuts where you can restart the daemon (e.g Create a personal Automation which starts when the device is connected to a charger, then start the ChargeLimiter daemon — this can be set where it will happen automatically without user input).

![image](https://github.com/lich4/ChargeLimiter/assets/88598340/0e10c11a-d081-4665-afce-1d4c80fdc75b)

Is it possible for this to be implemented?

**Comment by lich4** [comment]
Yes, It's possible, after a reboot, WiFi and Bluetooth will be enabled, you can consider that trigger.
