### ISSUE TITLE
测了一下插电即充模式下有个疑问

### ISSUE THREAD

**Issue by Saber-CC** [lich4/ChargeLimiter#71]
看文档说电量插电即充模式下，低于设定值时开始充电(为禁流设计)。我目前不管设置低于多少插上都会充电，那这个设计是用在什么场景下的。
那如果我想在低于80电量的时候就充电，然后到80停冲。我应该把这个额度放到80吗？但是默认的20也支持我这个使用场景，所以现在有点疑问🤔这个"低于设定值时开始充电(为禁流设计)"的设计在于什么使用场景

**Comment by lich4** [comment]
1. 有的小白就是看不到“重新插拔”的重新二字导致没电关机，所以加的预防措施
2. 一直连电的话，禁流后电池电量会降，所以得有个恢复充电机制

**Comment by Saber-CC** [comment]
> 1. 有的小白就是看不到“重新插拔”的重新二字导致没电关机，所以加的预防措施
> 2. 一直连电禁流的话(如整夜充电)，电池电量会降，所以得有个恢复充电机制

噢噢，谢谢作者回复🙏。还想好奇请教一下SmartBattery和智能停充大致逻辑有无，我翻了一下文档和issue没有看见细说的。

**Comment by lich4** [comment]
那是俩内部接口可以忽略，高级里的普通人全关就行了
