### ISSUE TITLE
Wish: Replace "CL v number" with current, in floating window

### ISSUE THREAD

**Issue by mailinglists35** [lich4/ChargeLimiter#72]
Hi,

Thank you again for this genius work!

I like the floating window. It proves very useful to view the battery percent when some apps (Camera first to think about) go fullscreen and hide the standard status bar thus hiding the battery percent level.

I imagine a enhancement to it, since currently on the third line it alternates temperature and current:

Would it be possible to always show the current  in the first line, after the toggle symbol, replacing the "CL version" string with current?

So the result would be still three lines, but always see the current and temperature at the same time.

Thank you!

**Comment by mailinglists35** [comment]
Followup thought: is it possible to fit time in the line with battery percent? Or replace the CL version with hour and minute?

Again, when going full screen, the status bar time is hidden. While for showing the battery percent you could do a workaround by pulling the Control Center, this action does only show the battery and operator names in status bar, but not the time.

It would be awesome to always see the time, for the same use case of full screen apps.

I could even give up the temperature and prefer to see the hour and minute instead - the temperature I would feel it anyway with the hand holding the phone :) 

Thank you!

**Comment by lich4** [comment]
Yes, the third line shifts among temperature and current every 10 seconds currently. 
It can be done by providing a submenu under floatwindow menu for user to define which to show in each line, including the time you mentioned, maybe next version.
Thanks for your advice.
