### ISSUE TITLE
连接 smartbatterycase 问题

### ISSUE THREAD

**Issue by manchunfai** [lich4/ChargeLimiter#73]
现版本在连接 smartbatterycase 后，无法维持在设定充电限制，会直接使用 smartbatterycase  内电量将手机电池充满。
![A53AB6E6-148E-4590-9676-2862B6BAA5D6](https://github.com/user-attachments/assets/3ecb02ae-2cf0-45ed-af8b-1640b0777bb5)
![E2147CC2-B38F-4A22-8698-6EED5E8EABF2](https://github.com/user-attachments/assets/49d8bccb-18dd-4c75-a36b-a1d51a8c85e5)

**Comment by lich4** [comment]
因为我没有SBC，所以无法为其单独开发，也无法测试停充在SBC这种硬件上的可行性。
目前也没购买SBC以完成CL硬件支持的计划，(iOS只是我开发用，平时用安卓)。
如果任何人有兴趣有条件的都可参与CL的开发，提交代码

**Comment by manchunfai** [comment]
你好，谢谢你的来信，明俊晖已收到你的信息。

**Comment by manchunfai** [comment]
你好，谢谢你的来信，明俊晖已收到你的信息。
