### ISSUE TITLE
温控在50%电量前不生效

### ISSUE THREAD

**Issue by watanaReborn** [lich4/ChargeLimiter#77]
开始充电设置的是20%，但是在插上充电器后会一直充电到50%，这期间温度超过设置的上限（35摄氏度）也不会停止。在50%电量后，温控开始生效。
另外，如果开启在停充时禁流时，温控可以在全阶段生效。

iPhone 13 pro max, iOS 15.4.1

**Comment by watanaReborn** [comment]
{
  "Battery": {
    "CurrentCapacity": 37,
    "UpdateTime": 1724641827,
    "Amperage": 3850,
    "PostDischargeWaitSeconds": 120,
    "InstantAmperage": 3875,
    "BatteryInstalled": true,
    "AppleRawCurrentCapacity": 1468,
    "Temperature": 3909,
    "BootVoltage": 4152,
    "Voltage": 4074,
    "CycleCount": 431,
    "PostChargeWaitSeconds": 120,
    "NominalChargeCapacity": 3930,
    "ExternalChargeCapable": true,
    "DesignCapacity": 4325,
    "AdapterDetails": {
      "Watts": 20,
      "Description": "pd charger",
      "Current": 2220,
      "Voltage": 9000,
      "IsWireless": false
    },
    "IsCharging": true,
    "ExternalConnected": true
  },
  "System": {
    "sysver": "15.4.1",
    "devmodel": "iPhone14,3"
  },
  "Config": {
    "adv_skip_wait": false,
    "adv_limit_inflow_mode": "moderate",
    "acc_charge_airmode": true,
    "acc_charge": false,
    "lang": "",
    "mode": "charge_on_plug",
    "acc_charge_lpm": true,
    "update_freq": 1,
    "charge_below": 20,
    "acc_charge_bright": false,
    "acc_charge_blue": false,
    "adv_prefer_smart": false,
    "adv_thermal_mode_lock": false,
    "floatwnd": false,
    "charge_temp_below": 30,
    "serv_boot": 1724641174,
    "enable": true,
    "charge_above": 79,
    "enable_temp": true,
    "thermal_simulate_mode": "nominal",
    "adv_limit_inflow": false,
    "devmodel": "iPhone14,3",
    "adv_disable_inflow": false,
    "ppm_simulate_mode": "off",
    "sysver": "15.4.1",
    "charge_temp_above": 35,
    "adv_predictive_inhibit_charge": true,
    "action": "",
    "ver": "1.6",
    "sys_boot": 1724515741,
    "adv_def_thermal_mode": "off",
    "temp_mode": 0,
    "acc_charge_wifi": false,
    "use_smart": false,
    "floatwnd_auto": false,
    "adv_thermal_avail": true
  }
}

**Comment by lich4** [comment]
出现这种问题之后,重点在于确定是否“硬件停充功能失灵” 导致, 还是短时间内温控不精确导致的. 如果是前者, 可自行根据日志和对比测试法排查.从日志可以确认硬件停充是否失灵(出现很多重复条目),同时可以在停充不正常操作手动停充按钮进一步验证硬件停充是否失灵. 如果存在硬件失灵,就是和CL不兼容,这种情况我个人是不建议使用的
