### ISSUE TITLE
Auto Brightness Toggled On After Minimize Brightness

### ISSUE THREAD

**Issue by vn1kk** [lich4/ChargeLimiter#78]
After you start charging with "Minimize Brightness" and "Speedup Charging" enabled, it turns brightness down but also turns on Auto Brightness. It doesn't happen instantly, but somewhere between 2 - 10 minutes after you start. It's annoying because auto-brightness is terrible.

**Comment by lich4** [comment]
Currently it will turn on it when stop charging triggered, will be fixed in next version

**Comment by lich4** [comment]
Fixed in v1.7
